enableGlobalCache: true
enableStrictSsl: false
nodeLinker: node-modules

npmScopes:
  aleacsys-online:
    npmRegistryServer: "https://verdaccio.cluster.gp.be/"
  gp:
    npmRegistryServer: "https://verdaccio.cluster.gp.be/"
  gp-types:
    npmRegistryServer: "https://verdaccio.cluster.gp.be/"
